version: '3.8'

services:
  frontend:
    build:
      context: ./zythologue-front-jn
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./BACK-API
    ports:
      - "3000:3000"
    environment:
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_HOST=database
      - DB_DATABASE=your_db_name
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
