services:
  # frontend:
  #   build:
  #     context: ./zythologue-front-jn
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=zytho
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=zytho
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d/

volumes:
  db_data:
